* webUI Overview should show correct port now. not using internal functions * pia-start and pia-daemon commands now work with new ovpn file locations but do not support port lookup yet

diff --git a/pia-start b/pia-start
--- a/pia-start
+++ b/pia-start
@@ -66,18 +66,27 @@ if [ -f "/pia/ovpn/$filename.ovpn" ]; then
 	check_repair_internet
 
 
-	echo -e "[info] "$(date +"%Y-%m-%d %H:%M:%S")\
-		"- establishing a VPN connection to $filename."
-	echo -e "\tsee ${bold}/pia/cache/session.log${normal} for details"
-    echo $(date +"%a %b %d %H:%M:%S %Y")" connecting to $filename" > /pia/cache/session.log
+    #get the provider / directory name
+    VPNprovider=`echo "$filename" | gawk -F"/" '{print $1}'`
 
-    #this is a hack until I come up with a good way to providers dynamically
+    #start openVPN session
     if [ -f "/pia/ovpn/$filename.ovpn" ]; then
-      echo "pia" > /pia/cache/provider.txt
+      echo -e "[info] "$(date +"%Y-%m-%d %H:%M:%S")\
+          "- establishing a VPN connection to $filename."
+      echo -e "\tsee ${bold}/pia/cache/session.log${normal} for details"
+      echo $(date +"%a %b %d %H:%M:%S %Y")" connecting to $filename" > /pia/cache/session.log
+
+      echo "$VPNprovider" > /pia/cache/provider.txt
       openvpn "/pia/ovpn/$filename.ovpn" &>> /pia/cache/session.log &
+
     else
-      echo "frootvpn" > /pia/cache/provider.txt
-      openvpn "/pia/ovpn/frootvpn/$filename.ovpn" &>> /pia/cache/session.log &
+      echo -e "[\e[1;31mfail\e[0m] "$(date +"%Y-%m-%d %H:%M:%S")\
+          "- specified file not found in pia-start - /pia/ovpn/$filename.ovpn"
+      echo -e "[\e[1;31mfail\e[0m] "$(date +"%Y-%m-%d %H:%M:%S")\
+          "- terminating...."
+      # remove old status.txt
+      rm -r '/pia/cache/status.txt' 2>/dev/null
+      exit 1
     fi
 
 
